'use client';

import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';

type Device = { npu_id:number; name?:string; health?:string; aicore_percent?:number; temperature_c?:number; power_w?:number; busy:boolean; hbm?:{used_mb?:number;total_mb?:number}; processes?:Array<{pid:number;name?:string;user?:string;container?:{name?:string}}> };
type Disk = { filesystem:string; mount:string; used_percent:number; available_bytes:number; total_bytes:number };
type Container = { id?:string; name?:string; image?:string; status?:string; state?:string };
type Snapshot = { status:string; collected_at:number; duration_ms?:number; error?:string; summary?:Record<string,number|null>; devices?:Device[]; disks?:Disk[]; mounts?:unknown[]; docker?:{available?:boolean;running?:number;containers?:Container[]} };
type Server = { id:string; name:string; host:string; port:number; username:string; tags:string[]; enabled:boolean; last_seen_at?:number; last_error?:string; status:string; snapshot?:Snapshot };
type Overview = { generated_at:number; totals:Record<string,number|null>; servers:Server[]; runtime:{mode:string;effective_interval:number;idle_interval:number;history_interval:number;active_viewers:number;collecting:boolean;last_cycle_at?:number;cycle_duration_ms?:number;allowed_intervals:number[]} };
type HistoryPoint = { bucket:number; cpu_percent?:number; npu_util_percent?:number; memory_percent?:number; hbm_percent?:number; disk_max_percent?:number };

const API = '';
const emptyOverview: Overview = { generated_at:0, totals:{servers:0,online_servers:0,npu_count:0,busy_npu_count:0,idle_npu_count:0,hbm_used_mb:0,hbm_total_mb:0,npu_util_percent:null}, servers:[], runtime:{mode:'idle',effective_interval:120,idle_interval:120,history_interval:30,active_viewers:0,collecting:false,allowed_intervals:[1,5,10,30]} };

function number(value: number | null | undefined, suffix = '') { return value == null ? '—' : `${Math.round(value)}${suffix}`; }
function bytes(value:number|null|undefined) { if(value==null) return '—'; const units=['B','KB','MB','GB','TB']; let size=value,index=0; while(size>=1024&&index<units.length-1){size/=1024;index++;} return `${size>=10||index<2?size.toFixed(0):size.toFixed(1)} ${units[index]}`; }
function mb(value:number|null|undefined) { return value==null?'—':bytes(value*1024*1024); }
function timeAgo(ts?:number) { if(!ts)return '尚未采集'; const delta=Math.max(0,Math.floor(Date.now()/1000-ts)); if(delta<5)return '刚刚'; if(delta<60)return `${delta} 秒前`; if(delta<3600)return `${Math.floor(delta/60)} 分钟前`; return new Date(ts*1000).toLocaleString('zh-CN',{hour12:false}); }
function percent(used?:number|null,total?:number|null){ return used!=null&&total?Math.round(used*100/total):null; }

function TrendCanvas({points, metric}:{points:HistoryPoint[];metric:keyof HistoryPoint}) {
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{
    const canvas=ref.current;if(!canvas)return;const ratio=window.devicePixelRatio||1;const box=canvas.getBoundingClientRect();canvas.width=box.width*ratio;canvas.height=box.height*ratio;
    const ctx=canvas.getContext('2d');if(!ctx)return;ctx.scale(ratio,ratio);ctx.clearRect(0,0,box.width,box.height);
    ctx.strokeStyle='#e4e9e6';ctx.lineWidth=1;for(let y=12;y<box.height;y+=(box.height-24)/4){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(box.width,y);ctx.stroke();}
    const values=points.map(point=>Number(point[metric]??0));if(values.length<2)return;
    const coords=values.map((value,index)=>[index*box.width/(values.length-1),box.height-12-Math.max(0,Math.min(100,value))*(box.height-24)/100]);
    const gradient=ctx.createLinearGradient(0,0,0,box.height);gradient.addColorStop(0,'rgba(36,120,94,.25)');gradient.addColorStop(1,'rgba(36,120,94,0)');
    ctx.beginPath();ctx.moveTo(coords[0][0],box.height);coords.forEach(([x,y])=>ctx.lineTo(x,y));ctx.lineTo(coords.at(-1)![0],box.height);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();
    ctx.beginPath();coords.forEach(([x,y],index)=>index?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.strokeStyle='#177a5c';ctx.lineWidth=2;ctx.stroke();
  },[points,metric]);
  return <canvas className="trend-canvas" ref={ref} aria-label="历史趋势图" />;
}

export default function Dashboard(){
  const [overview,setOverview]=useState<Overview>(emptyOverview);
  const [tab,setTab]=useState<'overview'|'history'|'servers'>('overview');
  const [interval,setIntervalValue]=useState(10);
  const [error,setError]=useState('');
  const [modal,setModal]=useState(false);
  const [history,setHistory]=useState<HistoryPoint[]>([]);
  const [range,setRange]=useState('24h');
  const [metric,setMetric]=useState<keyof HistoryPoint>('npu_util_percent');
  const [result,setResult]=useState('');
  const clientId=useMemo(()=>`viewer_${crypto.randomUUID().replaceAll('-','')}`,[]);

  const load=useCallback(async()=>{try{const response=await fetch(`${API}/api/overview`,{cache:'no-store'});if(!response.ok)throw new Error(`API ${response.status}`);setOverview(await response.json());setError('');}catch(err){setError(err instanceof Error?err.message:'无法连接本地采集器');}},[]);
  const heartbeat=useCallback(async(visible=true)=>{try{await fetch(`${API}/api/viewers/${clientId}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({interval,visible})});}catch{}},[clientId,interval]);

  useEffect(()=>{const initial=window.setTimeout(()=>{void load();void heartbeat(!document.hidden);},0);const refresh=window.setInterval(load,interval*1000);const lease=window.setInterval(()=>heartbeat(!document.hidden),10000);const visibility=()=>heartbeat(!document.hidden);document.addEventListener('visibilitychange',visibility);return()=>{clearTimeout(initial);clearInterval(refresh);clearInterval(lease);document.removeEventListener('visibilitychange',visibility);};},[load,heartbeat,interval]);
  useEffect(()=>{if(tab!=='history')return;fetch(`${API}/api/history?range=${range}`,{cache:'no-store'}).then(r=>r.json()).then(data=>setHistory(data.points||[])).catch(()=>setHistory([]));},[tab,range,overview.generated_at]);

  async function addServers(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const lines=String(form.get('servers')||'').split(/\r?\n/).map(v=>v.trim()).filter(Boolean);const servers=lines.map(line=>{const [name,host,port='22',username='root',tags='']=line.split(',').map(v=>v.trim());return {name,host:host||name,port:Number(port),username,tags:tags?tags.split('|'):[]};});const passwords=String(form.get('passwords')||'').split(/\r?\n/).filter(Boolean);setResult('正在逐台检查密钥并尝试一次性密码…');try{const response=await fetch(`${API}/api/servers/batch`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({servers,passwords})});const data=await response.json();const ok=(data.results||[]).filter((item:{auth:{ok:boolean}})=>item.auth.ok).length;setResult(`已完成：${ok}/${servers.length} 台建立密钥连接。密码未保存。`);await load();}catch(err){setResult(err instanceof Error?err.message:'批量添加失败');}}
  async function action(path:string,method='POST',body?:object){await fetch(`${API}${path}`,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});await load();}

  const total=overview.totals;const hbmPercent=percent(total.hbm_used_mb,total.hbm_total_mb);
  return <main className="shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">N</span><span>NPU Fleet</span></div><nav aria-label="主导航">
      <button className={`nav-item ${tab==='overview'?'active':''}`} onClick={()=>setTab('overview')}>总览</button>
      <button className={`nav-item ${tab==='history'?'active':''}`} onClick={()=>setTab('history')}>历史报表</button>
      <button className={`nav-item ${tab==='servers'?'active':''}`} onClick={()=>setTab('servers')}>服务器管理</button>
    </nav><div className="collector-state"><span className={`pulse ${overview.runtime.collecting?'working':''}`} />{overview.runtime.mode==='interactive'?'交互采集中':'低频巡检中'}<br/><small>{overview.runtime.effective_interval} 秒一次 · {overview.runtime.active_viewers} 个活跃页面</small></div></aside>
    <section className="content"><header className="topbar"><div><p className="eyebrow">本地算力观测台</p><h1>{tab==='overview'?'集群实时总览':tab==='history'?'资源历史报表':'服务器纳管'}</h1></div><div className="top-actions"><label className="interval">刷新 <select value={interval} onChange={e=>setIntervalValue(Number(e.target.value))}>{[1,5,10,30].map(value=><option value={value} key={value}>{value}s</option>)}</select></label><span className={`live ${error?'offline':''}`}><i />{error?'API 离线':'实时'}</span><button onClick={()=>setModal(true)}>＋ 添加服务器</button></div></header>

      {tab==='overview'&&<><section className="metrics" aria-label="集群指标"><article><span>NPU 在线</span><strong>{number(total.npu_count)}<span> 张</span></strong><small>{number(total.online_servers)} / {number(total.servers)} 台服务器在线</small></article><article><span>平均 NPU 利用率</span><strong>{number(total.npu_util_percent,'%')}</strong><small>{overview.runtime.collecting?'正在更新':'采集已同步'}</small></article><article><span>HBM 已使用</span><strong>{number(hbmPercent,'%')}</strong><small>{mb(total.hbm_used_mb)} / {mb(total.hbm_total_mb)}</small></article><article><span>空闲设备</span><strong>{number(total.idle_npu_count)}<span> 张</span></strong><small className="good">宿主机 HBM + 进程联合判定</small></article></section>
      <section className="panel fleet-panel"><div className="panel-head"><div><h2>服务器</h2><p>{overview.runtime.last_cycle_at?`最近采集于 ${timeAgo(overview.runtime.last_cycle_at)}`:'等待首次采集'}</p></div><div className="legend"><span><i className="dot busy"/>繁忙</span><span><i className="dot idle"/>空闲</span></div></div>
        {overview.servers.length===0?<div className="empty"><strong>还没有纳管服务器</strong><p>批量粘贴主机信息，系统会优先尝试现有密钥，再依次使用本次提供的密码配置专用密钥。</p><button onClick={()=>setModal(true)}>添加第一批服务器</button></div>:<div className="host-grid">{overview.servers.map(server=><article className={`host-card ${server.status}`} key={server.id}><div className="host-head"><div><h3>{server.name}</h3><code>{server.username}@{server.host}:{server.port}</code></div><span className={server.status==='online'?'online':'offline-badge'}>{server.status==='online'?'在线':server.status==='pending'?'等待':'离线'}</span></div>{server.snapshot?.devices?.length?<div className="npu-row">{server.snapshot.devices.map(device=><span title={`NPU ${device.npu_id} · ${number(device.aicore_percent,'%')} · ${mb(device.hbm?.used_mb)} · ${number(device.temperature_c,'°C')} · ${number(device.power_w,'W')}`} className={`npu ${device.busy?'busy':'idle'}`} key={device.npu_id}>{device.npu_id}</span>)}</div>:<div className="host-error">{server.snapshot?.error||server.last_error||'等待首次 NPU 探查'}</div>}<div className="resource-row"><span>CPU <b>{number(server.snapshot?.summary?.cpu_percent,'%')}</b></span><span>内存 <b>{number(percent(server.snapshot?.summary?.memory_used_bytes,server.snapshot?.summary?.memory_total_bytes),'%')}</b></span><span>HBM <b>{number(percent(server.snapshot?.summary?.hbm_used_mb,server.snapshot?.summary?.hbm_total_mb),'%')}</b></span></div><div className="host-infra"><span>磁盘峰值 {number(server.snapshot?.summary?.disk_max_percent,'%')}</span><span>挂载 {number(server.snapshot?.mounts?.length)}</span><span>Docker {number(server.snapshot?.summary?.docker_running)}</span></div><div className="host-foot"><span>{timeAgo(server.snapshot?.collected_at||server.last_seen_at)}</span><button onClick={()=>action(`/api/servers/${server.id}/collect`)}>立即探查</button></div></article>)}</div>}
      </section><section className="lower-grid"><article className="panel chart-panel"><div className="panel-head"><div><h2>采集策略</h2><p>远程负载会随前台活跃状态自动调整</p></div><span className="range">{overview.runtime.mode==='interactive'?'前台模式':'无人值守'}</span></div><div className="strategy"><div><strong>{overview.runtime.effective_interval}s</strong><span>NPU / CPU / 内存</span></div><i/><div><strong>{overview.runtime.mode==='interactive'?'60s':`${overview.runtime.idle_interval}s`}</strong><span>磁盘 / 挂载 / Docker</span></div><i/><div><strong>{overview.runtime.history_interval}s</strong><span>历史写库下限</span></div></div></article><article className="panel health-panel"><div className="panel-head"><div><h2>基础设施提醒</h2><p>磁盘、挂载与容器</p></div></div>{overview.servers.flatMap(server=>(server.snapshot?.disks||[]).filter(disk=>disk.used_percent>=80).map(disk=><div className="health-item" key={`${server.id}${disk.mount}`}><span className="health-icon warn">!</span><div><b>{server.name} · {disk.mount}</b><small>磁盘已使用 {disk.used_percent}%</small></div><strong>{bytes(disk.available_bytes)} 可用</strong></div>)).slice(0,3)}{!overview.servers.some(server=>(server.snapshot?.disks||[]).some(disk=>disk.used_percent>=80))&&<div className="health-empty"><span className="health-icon ok">✓</span><div><b>暂无高水位告警</b><small>阈值为磁盘使用率 80%</small></div></div>}</article></section></>}

      {tab==='history'&&<section className="history-layout"><article className="panel history-main"><div className="panel-head"><div><h2>聚合趋势</h2><p>SQLite 历史数据按时间窗口自动分桶</p></div><div className="filters"><select value={metric} onChange={e=>setMetric(e.target.value as keyof HistoryPoint)}><option value="npu_util_percent">NPU 利用率</option><option value="hbm_percent">HBM 占用</option><option value="cpu_percent">CPU 利用率</option><option value="memory_percent">内存占用</option><option value="disk_max_percent">磁盘最高水位</option></select><select value={range} onChange={e=>setRange(e.target.value)}>{['1h','6h','24h','7d','30d','90d'].map(value=><option key={value}>{value}</option>)}</select></div></div><TrendCanvas points={history} metric={metric}/><div className="history-axis"><span>{history.length?new Date(history[0].bucket*1000).toLocaleString('zh-CN'):'暂无数据'}</span><span>{history.length?new Date(history.at(-1)!.bucket*1000).toLocaleString('zh-CN'):''}</span></div></article><aside className="panel report-summary"><h2>窗口摘要</h2>{(['npu_util_percent','hbm_percent','cpu_percent','memory_percent'] as const).map(key=>{const values=history.map(point=>point[key]).filter((value):value is number=>value!=null);return <div className="summary-row" key={key}><span>{{npu_util_percent:'NPU 平均',hbm_percent:'HBM 平均',cpu_percent:'CPU 平均',memory_percent:'内存平均'}[key]}</span><strong>{values.length?number(values.reduce((a,b)=>a+b,0)/values.length,'%'):'—'}</strong></div>})}<p className="report-note">原始高频刷新只用于当前页面。历史数据按写库下限保存，并在查询时分桶，减少长期存储和探查压力。</p></aside></section>}

      {tab==='servers'&&<section className="panel server-table"><div className="panel-head"><div><h2>已纳管服务器</h2><p>密码仅用于首次密钥引导，不写入数据库或日志</p></div><button className="secondary" onClick={()=>action('/api/collect')}>全部探查</button></div>{overview.servers.length===0?<div className="empty"><strong>服务器列表为空</strong><button onClick={()=>setModal(true)}>批量添加</button></div>:<div className="table-wrap"><table><thead><tr><th>服务器</th><th>连接</th><th>标签</th><th>最近在线</th><th>状态</th><th>操作</th></tr></thead><tbody>{overview.servers.map(server=><tr key={server.id}><td><b>{server.name}</b></td><td><code>{server.username}@{server.host}:{server.port}</code></td><td>{server.tags.join(' · ')||'—'}</td><td>{timeAgo(server.last_seen_at)}</td><td><span className={server.status==='online'?'online':'offline-badge'}>{server.enabled?(server.status==='online'?'在线':'待检查'):'已暂停'}</span></td><td className="row-actions"><button onClick={()=>action(`/api/servers/${server.id}`,'PUT',{enabled:!server.enabled})}>{server.enabled?'暂停':'启用'}</button><button className="danger" onClick={()=>confirm(`移除 ${server.name}？历史数据也会删除。`)&&action(`/api/servers/${server.id}`,'DELETE')}>移除</button></td></tr>)}</tbody></table></div>}</section>}
    </section>
    {modal&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="add-title"><div className="modal-head"><div><p className="eyebrow">批量纳管</p><h2 id="add-title">添加 NPU 服务器</h2></div><button aria-label="关闭" onClick={()=>setModal(false)}>×</button></div><form onSubmit={addServers}><label>服务器列表 <span>每行：名称, 主机, 端口, 用户, 标签1|标签2</span><textarea name="servers" required rows={7} placeholder={'atlas-a3-01, 10.18.4.21, 22, root, A3|训练\natlas-a2-07, 10.18.4.37, 22, root, A2'} /></label><label>一次性密码候选 <span>可选，每行一个；仅在本次请求内按顺序尝试</span><textarea name="passwords" rows={4} autoComplete="new-password" spellCheck={false}/></label><div className="security-note"><b>连接策略</b><p>先检查已有密钥；失败后才尝试候选密码。成功后安装项目专用 Ed25519 公钥，后续采集只使用密钥。Host Key 变化会中止连接。</p></div>{result&&<p className="form-result">{result}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setModal(false)}>关闭</button><button type="submit">开始检查并添加</button></div></form></section></div>}
  </main>;
}
